#!/usr/bin/env python3
"""Build evidence/agents/INDEX.md: one row per agent report (stdlib only).

Columns: agent id (the report's file name), area (from the roster table in
evidence/coordination/roster.md), a one-line summary (the first paragraph of the
report's "Summary" section, flattened) and a link to the report. Roster agents without
a report are listed below the table. The output only changes when the inputs do.

  tools/evidence/collect_reports.py
  tools/evidence/collect_reports.py --agents-dir DIR --roster FILE --out FILE
"""

from __future__ import annotations

import argparse
import html
import os
import re
import subprocess
import sys
from pathlib import Path

INDEX_NAME = 'INDEX.md'
_HEADING = re.compile(r'^\s{0,3}(#{1,6})\s+(.*?)\s*#*\s*$')
_SUMMARY = re.compile(r'^(?:\d+[.)]\s*)?summary\b', re.IGNORECASE)
_LIST_MARK = re.compile(r'^(?:[-*+]|\d+[.)])\s+')
_CODE_SPAN = re.compile(r'(`+)(.+?)\1', re.DOTALL)


def cell(text: str) -> str:
    """Escape text for a markdown table cell; code spans are kept as they are."""
    parts, pos = [], 0
    for m in _CODE_SPAN.finditer(text):
        parts.append(html.escape(text[pos : m.start()], quote=False))
        parts.append(m.group(0))
        pos = m.end()
    parts.append(html.escape(text[pos:], quote=False))
    return ''.join(parts).replace('|', r'\|')


def split_row(line: str) -> list[str]:
    """Cells of a markdown table row (escaped pipes stay inside their cell)."""
    body = line.strip().removeprefix('|').removesuffix('|')
    return [c.strip().replace(r'\|', '|') for c in re.split(r'(?<!\\)\|', body)]


def read_roster(path: Path) -> dict[str, str]:
    """Map agent id -> area from the roster's markdown table(s)."""
    areas: dict[str, str] = {}
    if not path.is_file():
        return areas
    for line in path.read_text(encoding='utf-8').splitlines():
        if not line.lstrip().startswith('|'):
            continue
        cells = split_row(line)
        if len(cells) < 2:
            continue
        agent = cells[0].strip('`* ')
        if not agent or agent.lower() == 'id' or set(agent) <= set(':- '):
            continue
        areas[agent] = cells[1]
    return areas


def first_paragraph(lines: list[str]) -> str:
    """The first paragraph of lines (stops at a blank line, heading or code fence)."""
    para: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith(('```', '~~~')):
            break
        if not stripped or _HEADING.match(line):
            if para:
                break
            continue
        para.append(_LIST_MARK.sub('', stripped))
    return ' '.join(' '.join(para).split())


def summary_of(report: Path) -> tuple[str, bool]:
    """(first paragraph of the Summary section, whether that section exists).

    Without a Summary section, the first paragraph of the report is used instead.
    """
    lines = report.read_text(encoding='utf-8').splitlines()
    for i, line in enumerate(lines):
        m = _HEADING.match(line)
        if m and _SUMMARY.match(m.group(2)):
            level = len(m.group(1))
            end = len(lines)
            for j in range(i + 1, len(lines)):
                n = _HEADING.match(lines[j])
                if n and len(n.group(1)) <= level:
                    end = j
                    break
            return first_paragraph(lines[i + 1 : end]), True
    return first_paragraph(lines), False


def render(agents_dir: Path, roster: Path, out: Path) -> tuple[str, int, list[str]]:
    areas = read_roster(roster)
    reports = sorted(
        p
        for p in agents_dir.glob('*.md')
        if p.name.upper() != INDEX_NAME and p.resolve() != out.resolve()
    )

    def rel(path: Path) -> str:
        return Path(os.path.relpath(path.resolve(), out.parent.resolve())).as_posix()

    lines = [
        '# Agent reports',
        '',
        (
            'One report per agent, written by the agent itself. Areas come from the '
            f'[roster]({rel(roster)}); summaries are the first paragraph of each '
            "report's Summary section. Generated by "
            '`tools/evidence/collect_reports.py`.'
        ),
        '',
        '| Agent | Area | Summary | Report |',
        '| :-- | :-- | :-- | :-- |',
    ]
    for report in reports:
        agent = report.stem
        summary, found = summary_of(report)
        if not found:
            summary = f'_(no Summary section)_ {summary}'.rstrip()
        lines.append(
            f'| {cell(agent)} | {cell(areas.get(agent, "-"))} | {cell(summary)} '
            f'| [{report.name}]({rel(report)}) |'
        )
    missing = sorted(set(areas) - {r.stem for r in reports})
    lines.append('')
    if missing:
        names = ', '.join(f'`{a}`' for a in missing)
        lines.append(f'Roster agents without a report ({len(missing)}): {names}.')
    else:
        lines.append('Every roster agent has a report.')
    return '\n'.join(lines) + '\n', len(reports), missing


def _repo_root() -> Path:
    return Path(
        subprocess.run(
            ['git', 'rev-parse', '--show-toplevel'],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument('--agents-dir', type=Path, help='directory with <agent-id>.md')
    p.add_argument('--roster', type=Path, help='roster markdown file')
    p.add_argument('--out', type=Path, help='index file to write')
    args = p.parse_args(argv)
    agents_dir = args.agents_dir or _repo_root() / 'evidence' / 'agents'
    roster = args.roster or _repo_root() / 'evidence' / 'coordination' / 'roster.md'
    out = args.out or agents_dir / INDEX_NAME
    if not agents_dir.is_dir():
        print(f'collect_reports: no directory {agents_dir}', file=sys.stderr)
        return 1
    if not roster.is_file():
        print(f'collect_reports: warning: no roster at {roster}', file=sys.stderr)

    text, n, missing = render(agents_dir, roster, out)
    data = text.encode('utf-8')
    if out.exists() and out.read_bytes() == data:
        status = 'unchanged'
    else:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)
        status = 'written'
    print(f'collect_reports: {out} {status} ({n} reports, {len(missing)} missing)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
